baseURL = "https://bushfriends.netlify.app/"
title = "Bushfriends"
theme = "hugo-theme-m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Bushfriends"
  description = "IS415 G1T1 - Analysing the spread of Dengue cases in Singapore (2020) admist the transition to the Circuit Breaker period imposed by the Singapore Government"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = ""
  #[[params.social]]
  #  name = "twitter"
  #  url = "https://twitter.com/gohugoio"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
